server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates: # ??
            - Path=/api/user/** # api/user/ ?? ??? ????
          uri: lb://USER-SERVICE # ??? ???? APP-USER? ??? ???? ??? ???.

        - id: product-service
          predicates:
            - Path=/api/product/**
          uri: lb://PRODUCT-SERVICE

        - id: order-service
          predicates:
            - Path=/api/order/**
          uri: lb://ORDER-SERVICE

##          filters:
##            # url ???
##            # ?<???>? ?? ??? ???? ???? ??? ? ??? ??. ()? ??? ?? ?? -> segment? (.*)? ??
##            # ??(,)? ???? ?? url? ??? url? ?????.
##            # ?? ?? ??? ??? ${???}?? url ???? ?? / ?????? ?? ??.
##            - RewritePath=/first-service/(?<segment>.*), /$\{segment}